name: Publish ffmpeg-dev-pod image
on:
  workflow_dispatch:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'dev-pod/Dockerfile'
      - '.github/workflows/dev-pod.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'dev-pod/Dockerfile'
      - '.github/workflows/dev-pod.yaml'
jobs:
  build:
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      registry: ghcr.io/bryopsida
      image_name: ffmpeg-dev-pod
      codeql_enabled: false
      context: dev-pod/